[build]
  command = "CI= npm run build"
  publish = "public"

[dev]
  command = "npm run server"

[build.environment]
  NODE_VERSION = "18.15.0"

[[redirects]]
  from = "/*"
  to = "http://localhost:3000"
  status = 200